xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
xdotool key ctrl+shift+t;
xdotool type 'tmux new';
xdotool key KP_Enter;
